# Generated by Django 2.1.7 on 2019-03-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='teachers',
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=1, verbose_name='课时'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='api.Teacher', verbose_name='课程讲师'),
        ),
    ]
